<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Allows users to view the sidebar widget.' => 'Erlaubt Benutzern, das Sidebar-Widget anzuzeigen.',
    'Show the sidebar widget' => 'Anzeige des Sidebar Widgets',
    '<strong>Space</strong> subscribers' => '<strong>Space</strong>-Abonnenten',
    '<strong>Subscribers</strong>' => 'Abonnenten',
    '<strong>Subscriptions</strong> module configuration' => '<strong>Abonnements</strong> Modul Konfiguration',
    'Adds a snippet for showing up subscribers.' => 'Fügt ein Widget zum Anzeigen von Abonnenten hinzu.',
    'Edit <strong>max shown users</strong> in subscribers-list and <strong>sort order</strong> of the widget' => 'Bearbeiten Sie <strong>die max. Anzahl angezeigter Benutzer</strong> in der Liste und die <strong>Sortierreihenfolge</strong> des Widgets',
    'Max user items' => 'Maximal angezeigte Benutzer',
    'Show all' => 'Alle anzeigen',
    'Sort order' => 'Sortierreihenfolge',
    'Subscriptions' => 'Abonnements',
];
